#!/system/bin/sh

UKM=/system/UKM;
BB=$UKM/busybox;

UCI_CONFIG=$UKM/config.json;
UCI_ACTION=$UKM/actions/;
DEBUG=$UKM/debug;
SYNAPSE_SD_DIR=/sdcard/Synapse;

if [ ! -f $UCI_CONFIG ]; then
	$BB mount -t rootfs -o rw,remount rootfs;
	$BB chmod -R 755 $UCI_ACTION;

	[ ! -d "$SYNAPSE_SD_DIR/UKM" ] && $BB mkdir -p "$SYNAPSE_SD_DIR/UKM";
	KERNEL_CURR=`$BB cat /proc/version 2> /dev/null`;
	
	if [ ! -f "$SYNAPSE_SD_DIR/UKM/last_kernel" ]; then
		$BB rm -R /data/data/com.af.synapse/databases;
		$BB echo "$KERNEL_CURR" > $SYNAPSE_SD_DIR/UKM/last_kernel;
	else
		KERNEL_LAST=`$BB cat $SYNAPSE_SD_DIR/UKM/last_kernel 2> /dev/null`;
		
		if [ "$KERNEL_CURR" != "$KERNEL_LAST" ]; then
			$BB rm -R /data/data/com.af.synapse/databases;
			$BB echo "$KERNEL_CURR" > $SYNAPSE_SD_DIR/UKM/last_kernel;
		fi
	fi
	
	if [ ! -f $DEBUG/last_kmsg ]; then
		LAST_KMSG=`$BB tail -n 1 /proc/last_kmsg 2> /dev/null`;
		$BB echo $LAST_KMSG > $DEBUG/last_kmsg;
	fi
	
	source $UKM/config.json.generate > $UCI_CONFIG;
	
	$BB mount -t rootfs -o ro,remount rootfs;
fi;

case "${1}" in
  config)
		$BB cat $UCI_CONFIG;;
  configpath)
		$BB echo $UCI_CONFIG;;
  actionpath)
		$BB echo $UCI_ACTION;;
  reset)
		$BB mount -t rootfs -o rw,remount rootfs;
		$BB rm -f $UCI_CONFIG;
		$BB mount -t rootfs -o ro,remount rootfs;;
esac;
